# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tkafka/Dev/weathergraph/fontbm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tkafka/Dev/weathergraph/fontbm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tkafka/Dev/weathergraph/fontbm/CMakeFiles /Users/tkafka/Dev/weathergraph/fontbm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tkafka/Dev/weathergraph/fontbm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fontbm

# Build rule for target.
fontbm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fontbm
.PHONY : fontbm

# fast build rule for target.
fontbm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/build
.PHONY : fontbm/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

src/App.o: src/App.cpp.o
.PHONY : src/App.o

# target to build an object file
src/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/App.cpp.o
.PHONY : src/App.cpp.o

src/App.i: src/App.cpp.i
.PHONY : src/App.i

# target to preprocess a source file
src/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/App.cpp.i
.PHONY : src/App.cpp.i

src/App.s: src/App.cpp.s
.PHONY : src/App.s

# target to generate assembly for a file
src/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/App.cpp.s
.PHONY : src/App.cpp.s

src/FontInfo.o: src/FontInfo.cpp.o
.PHONY : src/FontInfo.o

# target to build an object file
src/FontInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/FontInfo.cpp.o
.PHONY : src/FontInfo.cpp.o

src/FontInfo.i: src/FontInfo.cpp.i
.PHONY : src/FontInfo.i

# target to preprocess a source file
src/FontInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/FontInfo.cpp.i
.PHONY : src/FontInfo.cpp.i

src/FontInfo.s: src/FontInfo.cpp.s
.PHONY : src/FontInfo.s

# target to generate assembly for a file
src/FontInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/FontInfo.cpp.s
.PHONY : src/FontInfo.cpp.s

src/ProgramOptions.o: src/ProgramOptions.cpp.o
.PHONY : src/ProgramOptions.o

# target to build an object file
src/ProgramOptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/ProgramOptions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramOptions.cpp.o
.PHONY : src/ProgramOptions.cpp.o

src/ProgramOptions.i: src/ProgramOptions.cpp.i
.PHONY : src/ProgramOptions.i

# target to preprocess a source file
src/ProgramOptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/ProgramOptions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramOptions.cpp.i
.PHONY : src/ProgramOptions.cpp.i

src/ProgramOptions.s: src/ProgramOptions.cpp.s
.PHONY : src/ProgramOptions.s

# target to generate assembly for a file
src/ProgramOptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/ProgramOptions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramOptions.cpp.s
.PHONY : src/ProgramOptions.cpp.s

src/ProgramOptionsTest.o: src/ProgramOptionsTest.cpp.o
.PHONY : src/ProgramOptionsTest.o

# target to build an object file
src/ProgramOptionsTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramOptionsTest.cpp.o
.PHONY : src/ProgramOptionsTest.cpp.o

src/ProgramOptionsTest.i: src/ProgramOptionsTest.cpp.i
.PHONY : src/ProgramOptionsTest.i

# target to preprocess a source file
src/ProgramOptionsTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramOptionsTest.cpp.i
.PHONY : src/ProgramOptionsTest.cpp.i

src/ProgramOptionsTest.s: src/ProgramOptionsTest.cpp.s
.PHONY : src/ProgramOptionsTest.s

# target to generate assembly for a file
src/ProgramOptionsTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramOptionsTest.cpp.s
.PHONY : src/ProgramOptionsTest.cpp.s

src/catchMain.o: src/catchMain.cpp.o
.PHONY : src/catchMain.o

# target to build an object file
src/catchMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/catchMain.cpp.o
.PHONY : src/catchMain.cpp.o

src/catchMain.i: src/catchMain.cpp.i
.PHONY : src/catchMain.i

# target to preprocess a source file
src/catchMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/catchMain.cpp.i
.PHONY : src/catchMain.cpp.i

src/catchMain.s: src/catchMain.cpp.s
.PHONY : src/catchMain.s

# target to generate assembly for a file
src/catchMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/catchMain.cpp.s
.PHONY : src/catchMain.cpp.s

src/external/lodepng/lodepng.o: src/external/lodepng/lodepng.cpp.o
.PHONY : src/external/lodepng/lodepng.o

# target to build an object file
src/external/lodepng/lodepng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/lodepng/lodepng.cpp.o
.PHONY : src/external/lodepng/lodepng.cpp.o

src/external/lodepng/lodepng.i: src/external/lodepng/lodepng.cpp.i
.PHONY : src/external/lodepng/lodepng.i

# target to preprocess a source file
src/external/lodepng/lodepng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/lodepng/lodepng.cpp.i
.PHONY : src/external/lodepng/lodepng.cpp.i

src/external/lodepng/lodepng.s: src/external/lodepng/lodepng.cpp.s
.PHONY : src/external/lodepng/lodepng.s

# target to generate assembly for a file
src/external/lodepng/lodepng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/lodepng/lodepng.cpp.s
.PHONY : src/external/lodepng/lodepng.cpp.s

src/external/maxRectsBinPack/MaxRectsBinPack.o: src/external/maxRectsBinPack/MaxRectsBinPack.cpp.o
.PHONY : src/external/maxRectsBinPack/MaxRectsBinPack.o

# target to build an object file
src/external/maxRectsBinPack/MaxRectsBinPack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/maxRectsBinPack/MaxRectsBinPack.cpp.o
.PHONY : src/external/maxRectsBinPack/MaxRectsBinPack.cpp.o

src/external/maxRectsBinPack/MaxRectsBinPack.i: src/external/maxRectsBinPack/MaxRectsBinPack.cpp.i
.PHONY : src/external/maxRectsBinPack/MaxRectsBinPack.i

# target to preprocess a source file
src/external/maxRectsBinPack/MaxRectsBinPack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/maxRectsBinPack/MaxRectsBinPack.cpp.i
.PHONY : src/external/maxRectsBinPack/MaxRectsBinPack.cpp.i

src/external/maxRectsBinPack/MaxRectsBinPack.s: src/external/maxRectsBinPack/MaxRectsBinPack.cpp.s
.PHONY : src/external/maxRectsBinPack/MaxRectsBinPack.s

# target to generate assembly for a file
src/external/maxRectsBinPack/MaxRectsBinPack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/maxRectsBinPack/MaxRectsBinPack.cpp.s
.PHONY : src/external/maxRectsBinPack/MaxRectsBinPack.cpp.s

src/external/tinyxml2/tinyxml2.o: src/external/tinyxml2/tinyxml2.cpp.o
.PHONY : src/external/tinyxml2/tinyxml2.o

# target to build an object file
src/external/tinyxml2/tinyxml2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/tinyxml2/tinyxml2.cpp.o
.PHONY : src/external/tinyxml2/tinyxml2.cpp.o

src/external/tinyxml2/tinyxml2.i: src/external/tinyxml2/tinyxml2.cpp.i
.PHONY : src/external/tinyxml2/tinyxml2.i

# target to preprocess a source file
src/external/tinyxml2/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/tinyxml2/tinyxml2.cpp.i
.PHONY : src/external/tinyxml2/tinyxml2.cpp.i

src/external/tinyxml2/tinyxml2.s: src/external/tinyxml2/tinyxml2.cpp.s
.PHONY : src/external/tinyxml2/tinyxml2.s

# target to generate assembly for a file
src/external/tinyxml2/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/external/tinyxml2/tinyxml2.cpp.s
.PHONY : src/external/tinyxml2/tinyxml2.cpp.s

src/freeType/FtLibrary.o: src/freeType/FtLibrary.cpp.o
.PHONY : src/freeType/FtLibrary.o

# target to build an object file
src/freeType/FtLibrary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/freeType/FtLibrary.cpp.o
.PHONY : src/freeType/FtLibrary.cpp.o

src/freeType/FtLibrary.i: src/freeType/FtLibrary.cpp.i
.PHONY : src/freeType/FtLibrary.i

# target to preprocess a source file
src/freeType/FtLibrary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/freeType/FtLibrary.cpp.i
.PHONY : src/freeType/FtLibrary.cpp.i

src/freeType/FtLibrary.s: src/freeType/FtLibrary.cpp.s
.PHONY : src/freeType/FtLibrary.s

# target to generate assembly for a file
src/freeType/FtLibrary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/freeType/FtLibrary.cpp.s
.PHONY : src/freeType/FtLibrary.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/extractFileNameTest.o: src/utils/extractFileNameTest.cpp.o
.PHONY : src/utils/extractFileNameTest.o

# target to build an object file
src/utils/extractFileNameTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/extractFileNameTest.cpp.o
.PHONY : src/utils/extractFileNameTest.cpp.o

src/utils/extractFileNameTest.i: src/utils/extractFileNameTest.cpp.i
.PHONY : src/utils/extractFileNameTest.i

# target to preprocess a source file
src/utils/extractFileNameTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/extractFileNameTest.cpp.i
.PHONY : src/utils/extractFileNameTest.cpp.i

src/utils/extractFileNameTest.s: src/utils/extractFileNameTest.cpp.s
.PHONY : src/utils/extractFileNameTest.s

# target to generate assembly for a file
src/utils/extractFileNameTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/extractFileNameTest.cpp.s
.PHONY : src/utils/extractFileNameTest.cpp.s

src/utils/getNumberLenTest.o: src/utils/getNumberLenTest.cpp.o
.PHONY : src/utils/getNumberLenTest.o

# target to build an object file
src/utils/getNumberLenTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/getNumberLenTest.cpp.o
.PHONY : src/utils/getNumberLenTest.cpp.o

src/utils/getNumberLenTest.i: src/utils/getNumberLenTest.cpp.i
.PHONY : src/utils/getNumberLenTest.i

# target to preprocess a source file
src/utils/getNumberLenTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/getNumberLenTest.cpp.i
.PHONY : src/utils/getNumberLenTest.cpp.i

src/utils/getNumberLenTest.s: src/utils/getNumberLenTest.cpp.s
.PHONY : src/utils/getNumberLenTest.s

# target to generate assembly for a file
src/utils/getNumberLenTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/getNumberLenTest.cpp.s
.PHONY : src/utils/getNumberLenTest.cpp.s

src/utils/splitStrByDelim.o: src/utils/splitStrByDelim.cpp.o
.PHONY : src/utils/splitStrByDelim.o

# target to build an object file
src/utils/splitStrByDelim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/utils/splitStrByDelim.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/splitStrByDelim.cpp.o
.PHONY : src/utils/splitStrByDelim.cpp.o

src/utils/splitStrByDelim.i: src/utils/splitStrByDelim.cpp.i
.PHONY : src/utils/splitStrByDelim.i

# target to preprocess a source file
src/utils/splitStrByDelim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/utils/splitStrByDelim.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/splitStrByDelim.cpp.i
.PHONY : src/utils/splitStrByDelim.cpp.i

src/utils/splitStrByDelim.s: src/utils/splitStrByDelim.cpp.s
.PHONY : src/utils/splitStrByDelim.s

# target to generate assembly for a file
src/utils/splitStrByDelim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fontbm.dir/build.make CMakeFiles/fontbm.dir/src/utils/splitStrByDelim.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/splitStrByDelim.cpp.s
.PHONY : src/utils/splitStrByDelim.cpp.s

src/utils/splitStrByDelimTest.o: src/utils/splitStrByDelimTest.cpp.o
.PHONY : src/utils/splitStrByDelimTest.o

# target to build an object file
src/utils/splitStrByDelimTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/splitStrByDelimTest.cpp.o
.PHONY : src/utils/splitStrByDelimTest.cpp.o

src/utils/splitStrByDelimTest.i: src/utils/splitStrByDelimTest.cpp.i
.PHONY : src/utils/splitStrByDelimTest.i

# target to preprocess a source file
src/utils/splitStrByDelimTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/splitStrByDelimTest.cpp.i
.PHONY : src/utils/splitStrByDelimTest.cpp.i

src/utils/splitStrByDelimTest.s: src/utils/splitStrByDelimTest.cpp.s
.PHONY : src/utils/splitStrByDelimTest.s

# target to generate assembly for a file
src/utils/splitStrByDelimTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/utils/splitStrByDelimTest.cpp.s
.PHONY : src/utils/splitStrByDelimTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fontbm"
	@echo "... unit_tests"
	@echo "... src/App.o"
	@echo "... src/App.i"
	@echo "... src/App.s"
	@echo "... src/FontInfo.o"
	@echo "... src/FontInfo.i"
	@echo "... src/FontInfo.s"
	@echo "... src/ProgramOptions.o"
	@echo "... src/ProgramOptions.i"
	@echo "... src/ProgramOptions.s"
	@echo "... src/ProgramOptionsTest.o"
	@echo "... src/ProgramOptionsTest.i"
	@echo "... src/ProgramOptionsTest.s"
	@echo "... src/catchMain.o"
	@echo "... src/catchMain.i"
	@echo "... src/catchMain.s"
	@echo "... src/external/lodepng/lodepng.o"
	@echo "... src/external/lodepng/lodepng.i"
	@echo "... src/external/lodepng/lodepng.s"
	@echo "... src/external/maxRectsBinPack/MaxRectsBinPack.o"
	@echo "... src/external/maxRectsBinPack/MaxRectsBinPack.i"
	@echo "... src/external/maxRectsBinPack/MaxRectsBinPack.s"
	@echo "... src/external/tinyxml2/tinyxml2.o"
	@echo "... src/external/tinyxml2/tinyxml2.i"
	@echo "... src/external/tinyxml2/tinyxml2.s"
	@echo "... src/freeType/FtLibrary.o"
	@echo "... src/freeType/FtLibrary.i"
	@echo "... src/freeType/FtLibrary.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/extractFileNameTest.o"
	@echo "... src/utils/extractFileNameTest.i"
	@echo "... src/utils/extractFileNameTest.s"
	@echo "... src/utils/getNumberLenTest.o"
	@echo "... src/utils/getNumberLenTest.i"
	@echo "... src/utils/getNumberLenTest.s"
	@echo "... src/utils/splitStrByDelim.o"
	@echo "... src/utils/splitStrByDelim.i"
	@echo "... src/utils/splitStrByDelim.s"
	@echo "... src/utils/splitStrByDelimTest.o"
	@echo "... src/utils/splitStrByDelimTest.i"
	@echo "... src/utils/splitStrByDelimTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

